import type { Metadata } from "next";
import "./globals.css";
import "./fonts.css";
import "./print.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className="font-['Calibri']">{children}</body>
    </html>
  );
}
